parameters:
#    ponteiro_graphics_and_charts.example.class: Ponteiro\GraphicsAndChartsBundle\Example

services:
#    ponteiro_graphics_and_charts.example:
#        class: %ponteiro_graphics_and_charts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
